BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ABRASION_RAW" (
	"TEST_ID"	INTEGER NOT NULL,
	"SAMPLE_NUMBER"	INTEGER NOT NULL,
	"ATTRIBUTE"	TEXT NOT NULL,
	"VALUE"	REAL,
	PRIMARY KEY("TEST_ID","SAMPLE_NUMBER","ATTRIBUTE"),
	FOREIGN KEY("TEST_ID") REFERENCES "TEST_REPORT_INFO"("TEST_ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "ABSORPTION_RAW" (
	"TEST_ID"	INTEGER NOT NULL,
	"SAMPLE_NUMBER"	INTEGER NOT NULL,
	"ATTRIBUTE"	TEXT NOT NULL,
	"VALUE"	REAL,
	PRIMARY KEY("TEST_ID","SAMPLE_NUMBER","ATTRIBUTE"),
	FOREIGN KEY("TEST_ID") REFERENCES "TEST_REPORT_INFO"("TEST_ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "CLIENT" (
	"CLIENT_ID"	INTEGER,
	"COMPANY_NAME"	TEXT NOT NULL,
	"BUYER"	TEXT,
	"COMPANY_ADDRESS"	TEXT,
	"PHONE_NUMBER"	TEXT,
	"EMAIL"	TEXT,
	"COUNTRY_OF_ORIGIN"	TEXT,
	PRIMARY KEY("CLIENT_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "EVAPORATION_RAW" (
	"TEST_ID"	INTEGER NOT NULL,
	"SAMPLE_NUMBER"	INTEGER NOT NULL,
	"ATTRIBUTE"	TEXT NOT NULL,
	"VALUE"	REAL,
	PRIMARY KEY("TEST_ID","SAMPLE_NUMBER","ATTRIBUTE"),
	FOREIGN KEY("TEST_ID") REFERENCES "TEST_REPORT_INFO"("TEST_ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "SPECIMEN" (
	"SPECIMEN_ID"	INTEGER,
	"SPECIMEN_DESCRIPTION"	TEXT,
	"SKU"	TEXT,
	"STYLE"	TEXT,
	"BASIS_WEIGHT"	TEXT,
	"COLOR"	TEXT,
	PRIMARY KEY("SPECIMEN_ID")
);
CREATE TABLE IF NOT EXISTS "TEST_REPORT_INFO" (
	"TEST_ID"	INTEGER,
	"ISSUE_DATE"	TEXT,
	"TEST_DESCRIPTION"	TEXT,
	"LOCATION"	TEXT,
	"OPERATOR_NAME"	TEXT,
	"TEST_NAME"	TEXT,
	"TEST_TYPE"	TEXT,
	"TEST_RESULT"	TEXT,
	"CLIENT_ID"	INTEGER,
	"SPECIMEN_ID"	INTEGER,
	PRIMARY KEY("TEST_ID" AUTOINCREMENT),
	FOREIGN KEY("CLIENT_ID") REFERENCES "CLIENT"("CLIENT_ID") ON DELETE SET NULL,
	FOREIGN KEY("SPECIMEN_ID") REFERENCES "SPECIMEN"("SPECIMEN_ID") ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VERTICAL_WICKING_MODEL" (
	"TEST_ID"	INTEGER NOT NULL,
	"SAMPLE_NUMBER"	INTEGER NOT NULL,
	"TIME_UNIFORM"	REAL,
	"HEIGHT_MODEL"	REAL,
	"WICKING_MODEL"	REAL,
	PRIMARY KEY("TEST_ID","SAMPLE_NUMBER"),
	FOREIGN KEY("TEST_ID") REFERENCES "TEST_REPORT_INFO"("TEST_ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "VERTICAL_WICKING_RAW" (
	"TEST_ID"	INTEGER NOT NULL,
	"SAMPLE_NUMBER"	INTEGER NOT NULL,
	"TIME"	REAL,
	"HEIGHT"	REAL,
	PRIMARY KEY("TEST_ID","SAMPLE_NUMBER"),
	FOREIGN KEY("TEST_ID") REFERENCES "TEST_REPORT_INFO"("TEST_ID") ON DELETE CASCADE
);
CREATE VIEW EVAPORATION AS
SELECT
  TEST_ID,
  SAMPLE_NUMBER,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_WEIGHT'                 THEN VALUE END) AS FRAME_WEIGHT,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_WEIGHT_TIME'            THEN VALUE END) AS FRAME_WEIGHT_TIME,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_SAMPLE_WEIGHT'          THEN VALUE END) AS FRAME_SAMPLE_WEIGHT,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_SAMPLE_WEIGHT_TIME'     THEN VALUE END) AS FRAME_SAMPLE_WEIGHT_TIME,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_SAMPLE_WEIGHT_WET'      THEN VALUE END) AS FRAME_SAMPLE_WEIGHT_WET,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_SAMPLE_WEIGHT_WET_TIME' THEN VALUE END) AS FRAME_SAMPLE_WEIGHT_WET_TIME,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_SAMPLE_WEIGHT_DRY'      THEN VALUE END) AS FRAME_SAMPLE_WEIGHT_DRY,
  MAX(CASE WHEN ATTRIBUTE = 'FRAME_SAMPLE_WEIGHT_DRY_TIME' THEN VALUE END) AS FRAME_SAMPLE_WEIGHT_DRY_TIME
FROM EVAPORATION_RAW
GROUP BY TEST_ID, SAMPLE_NUMBER;
CREATE INDEX IF NOT EXISTS "idx_abr_raw_test_sample" ON "ABRASION_RAW" (
	"TEST_ID",
	"SAMPLE_NUMBER"
);
CREATE INDEX IF NOT EXISTS "idx_abs_raw_test_sample" ON "ABSORPTION_RAW" (
	"TEST_ID",
	"SAMPLE_NUMBER"
);
CREATE INDEX IF NOT EXISTS "idx_tri_client" ON "TEST_REPORT_INFO" (
	"CLIENT_ID"
);
CREATE INDEX IF NOT EXISTS "idx_tri_issue" ON "TEST_REPORT_INFO" (
	"ISSUE_DATE"
);
CREATE INDEX IF NOT EXISTS "idx_tri_specimen" ON "TEST_REPORT_INFO" (
	"SPECIMEN_ID"
);
CREATE INDEX IF NOT EXISTS "idx_wick_model_test_sample" ON "VERTICAL_WICKING_MODEL" (
	"TEST_ID",
	"SAMPLE_NUMBER"
);
CREATE INDEX IF NOT EXISTS "idx_wick_raw_test_sample" ON "VERTICAL_WICKING_RAW" (
	"TEST_ID",
	"SAMPLE_NUMBER"
);
COMMIT;
